

def fun():
    raise Exception("123")

print("123")
fun()
print("12355")